# Generated by Django 3.2.5 on 2021-08-07 03:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workstation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancerecords',
            name='rob',
        ),
        migrations.AddField(
            model_name='maintenancerecords',
            name='sort',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='故障类型'),
        ),
        migrations.AddField(
            model_name='maintenancerecords',
            name='workstation',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='工位'),
        ),
        migrations.AlterField(
            model_name='maintenancerecords',
            name='maintenance_worker',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='维修人员'),
        ),
    ]
