# Generated by Django 3.2.5 on 2021-08-15 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workstation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='sort',
        ),
        migrations.AddField(
            model_name='articles',
            name='sort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workstation.mysort', verbose_name='分类'),
        ),
    ]
