# Generated by Django 3.2.5 on 2021-08-04 14:24

from django.db import migrations, models
import utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ('workstation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=utils.utils.FilePath, verbose_name='图片'),
        ),
    ]
