# Generated by Django 3.2.5 on 2021-08-27 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workstation', '0002_auto_20210815_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='parts',
            name='hot',
            field=models.IntegerField(blank=True, null=True, verbose_name='热度'),
        ),
    ]
