# Generated by Django 3.2.5 on 2021-08-07 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workstation', '0002_auto_20210807_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerecords',
            name='device_type',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='设备'),
        ),
        migrations.AddField(
            model_name='maintenancerecords',
            name='duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='持续时间'),
        ),
        migrations.AddField(
            model_name='maintenancerecords',
            name='localLv1',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='一级地点'),
        ),
        migrations.AddField(
            model_name='maintenancerecords',
            name='localLv2',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='二级地点'),
        ),
        migrations.AddField(
            model_name='maintenancerecords',
            name='localLv3',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='三级地点'),
        ),
    ]
