# Generated by Django 3.2.5 on 2021-08-31 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workstation', '0002_auto_20210815_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerifyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='验证码')),
                ('email', models.EmailField(max_length=50, verbose_name='邮箱')),
                ('send_type', models.CharField(choices=[('register', '注册'), ('forget', '找回密码'), ('reset', '重置密码')], max_length=10, verbose_name='验证码类型')),
                ('send_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'emailcode',
            },
        ),
        migrations.RenameField(
            model_name='parts',
            old_name='part_file',
            new_name='part_img',
        ),
        migrations.RemoveField(
            model_name='parts',
            name='usefor',
        ),
        migrations.AddField(
            model_name='parts',
            name='desc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='parts',
            name='hot',
            field=models.IntegerField(blank=True, null=True, verbose_name='热度'),
        ),
        migrations.AddField(
            model_name='parts',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='收藏'),
        ),
        migrations.CreateModel(
            name='Part2User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(auto_now_add=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workstation.parts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('part', 'user')},
            },
        ),
    ]
