# Generated by Django 3.2.5 on 2021-08-27 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workstation', '0003_parts_hot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parts',
            old_name='part_file',
            new_name='part_img',
        ),
    ]
