# Generated by Django 3.2.5 on 2021-09-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workstation', '0003_auto_20210831_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parts',
            name='hot',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='热度'),
        ),
    ]
