# Generated by Django 3.2.5 on 2021-11-01 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workstation', '0004_alter_parts_hot'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmsMaintenanceRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localLv1', models.CharField(blank=True, max_length=16, null=True, verbose_name='一级地点')),
                ('localLv2', models.CharField(blank=True, max_length=16, null=True, verbose_name='二级地点')),
                ('localLv3', models.CharField(blank=True, max_length=16, null=True, verbose_name='三级地点')),
                ('car_model', models.CharField(blank=True, max_length=32, null=True, verbose_name='车型')),
                ('ng_car', models.IntegerField(blank=True, null=True, verbose_name='NG小车')),
                ('maintenance_record', models.TextField(blank=True, null=True, verbose_name='维修记录')),
                ('order_comments', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('closing_date', models.DateTimeField(auto_now=True, null=True, verbose_name='节点')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('order_status', models.IntegerField(blank=True, null=True, verbose_name='订单状态')),
                ('applicant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='emsmaintenancerecords_applicant_myuser', to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
            ],
        ),
    ]
