# Generated by Django 3.2.5 on 2021-08-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workstation', '0004_maintenancerecords_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerecords',
            name='maintenance_status',
            field=models.IntegerField(blank=True, choices=[(1, '完全修复'), (2, '临时修复')], null=True, verbose_name='故障状态'),
        ),
    ]
