# Generated by Django 3.2.5 on 2021-08-27 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workstation', '0004_rename_part_file_parts_part_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parts',
            name='usefor',
        ),
        migrations.AddField(
            model_name='parts',
            name='desc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='描述'),
        ),
    ]
