# Generated by Django 3.2.5 on 2021-08-11 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workstation', '0005_maintenancerecords_maintenance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerecords',
            name='need_summary',
            field=models.BooleanField(default=0, verbose_name='是否需要总结'),
        ),
    ]
