# Generated by Django 3.2.5 on 2021-08-30 03:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workstation', '0005_auto_20210827_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='parts',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
