# Generated by Django 3.2.5 on 2021-11-01 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workstation', '0005_emsmaintenancerecords'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='emsmaintenancerecords',
            table='emsmaintenance_records',
        ),
    ]
