# Generated by Django 3.2.5 on 2021-08-30 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workstation', '0008_parts_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parts',
            old_name='user',
            new_name='users',
        ),
    ]
