# Generated by Django 3.2.5 on 2021-08-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workstation', '0010_emailverifyrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_type',
            field=models.CharField(choices=[('register', '注册'), ('forget', '找回密码'), ('reset', '重置密码')], max_length=10, verbose_name='验证码类型'),
        ),
    ]
