# Generated by Django 3.2.5 on 2021-08-30 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workstation', '0011_alter_emailverifyrecord_send_type'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='emailverifyrecord',
            table='emailcode',
        ),
    ]
