# Generated by Django 3.2.5 on 2021-08-07 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phonenum',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='worknum',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='工号'),
        ),
    ]
